# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e908d024921e2e001cdbfa8ccdcf9ef18e0cc2af9073fb02d0ba56374f0983d2c746d3154df271ee60aad6fd84e4825ef85fa2f3ec3e261e63af9dae882eb4d

test:
  secret_key_base: 7a3b0c233309052b8ca8a4493ece07b5effaf03b5f67b4ddc91db7ec67a524e97dd2eb173601b5f66a402d90b8ace41df1d058f6503b92c6b2ce7d13bb900a35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
